name: Build and Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        racket-variant: ["BC", "CS"]

    steps:
    - uses: actions/checkout@v3.5.3
    - uses: Bogdanp/setup-racket@v1.10
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: current
        sudo: never
        dest: '${HOME}/racket'
        local_catalogs: $GITHUB_WORKSPACE
    - run: raco pkg update -i --no-setup htdp-lib htdp-doc htdp
    - name: Install htdp-test (depends on htdp-lib)
      run: raco pkg install --auto -i --skip-installed --no-setup htdp-test
    - run: raco setup --check-pkg-deps --pkgs htdp-lib htdp-doc htdp-test
    - name: Run tests
      run: xvfb-run raco test htdp-test
